language: perl
perl:
  - "5.8"
#   - "5.10"
#   - "5.12"
#   - "5.14"
#   - "5.16"
#   - "5.18"
  - "5.20"
matrix:
  include:
    - perl: 5.20
      env: COVERAGE=1
before_install:
  - cpanm --quiet --notest XML::XPath
  - cpanm --quiet --notest DBM::Deep
  - cpanm --quiet --notest Digest::MD5
  - cpanm --quiet --notest File::Find::Rule
  - cpanm --quiet --notest Spreadsheet::ParseExcel
  - cpanm --quiet --notest Text::CSV_XS
  - ./build-data.sh
  - eval $(curl https://travis-perl.github.io/init) --auto
