language: perl
perl:
  - "5.8"
  - "5.20"
matrix:
  include:
    - perl: "5.20"
      before_install:
        - cpanm --quiet --notest Devel::Cover::Report::Coveralls
        # eeuuww, repetition from the global 'before_install'
        - cpanm --quiet --notest XML::XPath
        - cpanm --quiet --notest DBM::Deep
        - cpanm --quiet --notest Digest::MD5
        - cpanm --quiet --notest File::Find::Rule
        - cpanm --quiet --notest Spreadsheet::ParseExcel
        - cpanm --quiet --notest Text::CSV_XS
        - ./build-data.sh
        # repetition ends here
      script: "perl Makefile.PL && make && cover -ignore blib/lib/Number/Phone/UK/Data.pm -ignore blib/lib/Number/Phone/StubCountry/??.pm -ignore blib/lib/Number/Phone/NANP/??.pm -test -report coveralls"
before_install:
  - cpanm --quiet --notest XML::XPath
  - cpanm --quiet --notest DBM::Deep
  - cpanm --quiet --notest Digest::MD5
  - cpanm --quiet --notest File::Find::Rule
  - cpanm --quiet --notest Spreadsheet::ParseExcel
  - cpanm --quiet --notest Text::CSV_XS
  - ./build-data.sh
